name: SMDUpdate
main: me.palapon2545.net.patch.pluginMain
version: 1.0.0
description: Add-on for SMDMain
author: p0N67a
depend: [SMDMain]
load: STARTUP
website: https://github.com/palapon2545/none
commands:
  patch:
       description: use to update SMDMain.
       usage: /patch (Need OP)
